name: Run Scraper and Deploy JSON to GitHub Pages

on:
  schedule:
    # Runs every weekday (Monday to Friday) at 13 AM UTC
    - cron: "0 13 * * 1-5"
  workflow_dispatch: # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configurar Python y ejecutar el scraper
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de que tengas un archivo requirements.txt

      - name: Run scraper
        run: |
          python -m app.main

      # Crear la carpeta `docs` para GitHub Pages y copiar los JSON
      - name: Prepare GitHub Pages output
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          cp data/*.json docs/  # Copia los JSON generados a `docs`

      # Configurar Git y hacer commit de los JSON generados
      - name: Commit files
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add docs/*.json
          git commit -m "Update JSON files from scraper"

      # Push al repositorio
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin main  # Asegúrate de que esté sincronizado antes del push
          git push origin HEAD:main
